const ROOM_SIZE = 50;
const MIN_EXTENSION_COORD = 5;
const MAX_EXTENSION_COORD = 44;
const MIN_LIFE = 500;
const MAX_LIFE = 3000;

module.exports = {ROOM_SIZE, MIN_EXTENSION_COORD, MAX_EXTENSION_COORD, MIN_LIFE, MAX_LIFE};
