const ROOM_SIZE = 50;
const MIN_EXTENSION_COORD = 5;
const MAX_EXTENSION_COORD = 44;
const MIN_LIFE = 250;
const MAX_LIFE = 1400;
const REPAIR_STOP_THRESHHOLD = 0.95;
const MAX_RENEW_CYCLES = {
    1: 5,
    2: 7,
    3: 9,
    4: 11,
    5: 13,
    6: 15,
    7: 17,
    8: 19
}

const DEFAULT_OPACITY = 0.75;
const DEFAULT_EXPLORATION_RANGE = 4;
const DEFAULT_EXPLOITATION_RANGE = 3;
const DEFAULT_REUSE_PATH = 10;
const LONG_JOURNEY_REUSE_PATH = 100;

module.exports = {ROOM_SIZE, MIN_EXTENSION_COORD, MAX_EXTENSION_COORD, MIN_LIFE, MAX_LIFE, MAX_RENEW_CYCLES, REPAIR_STOP_THRESHHOLD, DEFAULT_OPACITY, DEFAULT_EXPLORATION_RANGE, DEFAULT_REUSE_PATH, LONG_JOURNEY_REUSE_PATH, DEFAULT_EXPLOITATION_RANGE};
