const ROOM_SIZE = 50;
const MIN_EXTENSION_COORD = 5;
const MAX_EXTENSION_COORD = 44;
const MIN_LIFE = 250;
const MAX_LIFE = 1400;
const REPAIR_STOP_THRESHHOLD = 0.95;
const MAX_RENEW_CYCLES = {
    1: 3,
    2: 4,
    3: 5,
    4: 6,
    5: 7,
    6: 8,
    7: 9,
    8: 10
}

const DEFAULT_OPACITY = 0.75;

module.exports = {ROOM_SIZE, MIN_EXTENSION_COORD, MAX_EXTENSION_COORD, MIN_LIFE, MAX_LIFE, MAX_RENEW_CYCLES, REPAIR_STOP_THRESHHOLD, DEFAULT_OPACITY};
